document.write( '<div class=\"mobile_menu\"></div>\n' );
document.write( '<nav class=\"topnav\">\n' );
document.write( '\n' );
document.write( '<img class=\"logo\" src=\"/kepek/logok/15.jpg\" alt=\"logo\">' );
document.write( '\n' );
document.write( '    <div class=\"dropdown\">\n' );
document.write( '\n' );
document.write( '      <button><a href=\"/index.html#magyar_dialogikus_iskola\" id=\"navbar_dialogikus_iskola\">Dialogikus Iskola</a></button>\n' );
document.write( '\n' );
document.write( '      <div class=\"dropdown_content\">\n' );
document.write( '        <a href=\"/index.html#vadirat\" id=\"navbar_vadirat\">Vádirat</a>\n' );
document.write( '        <a href=\"/index.html#alapallas\" id=\"navbar_alapallas\">Alapállás</a>\n' );
document.write( '        <a href=\"/index.html#tortenet\" id=\"navbar_tortenet\">Történet</a>\n' );
document.write( '        <a href=\"/index.html#harmincas_evek\" id=\"navbar_harmincas_evek\">A \'30-as évek írásai</a>\n' );
document.write( '        <a href=\"/index.html#negyvenot_utan\" id=\"navbar_negyvenot_utan\">1945 után</a>\n' );
document.write( '      </div>\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '    <div class=\"dropdown\">\n' );
document.write( '\n' );
document.write( '      <button><a href=\"/beszelgetesek.html\" id=\"navbar_beszelgetesek_vitak_szeminariumok\">Beszélgetések, viták, szemináriumok</a></button>\n' );
document.write( '\n' );
document.write( '      <div class=\"dropdown_content\">\n' );
document.write( '        <a href=\"/beszelgetesek.html#csutortoki_beszelgetesek\" id=\"navbar_csutortoki_beszelgetesek\">Csütörtöki beszélgetések</a>\n' );
document.write( '        <a href=\"/beszelgetesek.html#szabo_lajos_szeminariumai\" id=\"navbar_szabo_lajos_szeminariumai\">Szabó Lajos szemináriumai</a>\n' );
document.write( '        <a href=\"/beszelgetesek.html#tabor_bela_preszokratikus_szeminariumai\" id=\"navbar_tabor_bela_preszokratikus_szeminariumai\">Tábor Béla preszókratikus szemináriumai</a>\n' );
document.write( '        <a href=\"/beszelgetesek.html#vitak\" id=\"navbar_vitak\">Viták</a>\n' );
document.write( '      </div>\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '  <div class=\"dropdown\">\n' );
document.write( '    <button><a href=\"/SZL/szabolajos.html\" id=\"navbar_szabo_lajos\">Szabó Lajos</a></button>\n' );
document.write( '\n' );
document.write( '    <div class=\"dropdown_content\">\n' );
document.write( '      <a href=\"/SZL/eletrajz/szabo_lajos_eletrajz.htm\" id=\"navbar_szabo_lajos_eletrajz\">Életrajz</a>\n' );
document.write( '      <a href=\"/SZL/irasok/\" id=\"navbar_szabo_lajos_irasok\">Írások</a>\n' );
document.write( '      <a href=\"/SZL/szeminariumi_eloadasok/\" id=\"navbar_szabo_lajos_szeminariumi_eloadasok\">Szemináriumi előadások</a>\n' );
document.write( '      <a href=\"/SZL/\" id=\"navbar_szabo_lajos_grafikak_kiallitasok\">Grafikák, kiállítások</a>\n' );
document.write( '      <a href=\"/SZL/\" id=\"navbar_szabo_lajos_dusseldorfi_beszelgetesek\">Düsseldorfi beszélgetések</a>\n' );
document.write( '      <a href=\"/SZL/\" id=\"navbar_szabo_lajos_konferenciak\">Konferenciák</a>\n' );
document.write( '      <a href=\"/SZL/\" id=\"navbar_szabo_lajos_bibliografia\">Bibliográfia</a>\n' );
document.write( '    </div>\n' );
document.write( '  </div>\n' );
document.write( '\n' );
document.write( '  <div class=\"dropdown\">\n' );
document.write( '    <button><a href=\"/taborbela/taborbela.html\" id=\"navbar_tabor_bela\">Tábor Béla</a></button>\n' );
document.write( '\n' );
document.write( '    <div class=\"dropdown_content\">\n' );
document.write( '      <a href=\"/horvathagnes/horvathagnes.html\" id=\"navbar_tabor_bela_eletrajz\">Életrajz</a>\n' );
document.write( '      <a href=\"/suranyilaszlo/suranyilaszlo.html\" id=\"navbar_tabor_bela_konyvek\">Könyvek</a>\n' );
document.write( '      <a href=\"/taboradam/taboradam.html\" id=\"navbar_tabor_bela_ostortenet\">\"Őstörténet\"</a>\n' );
document.write( '      <a href=\"/horvathagnes/horvathagnes.html\" id=\"navbar_tabor_bela_a_szimbolum_valsaga\">A szimbólum válsága</a>\n' );
document.write( '      <a href=\"/suranyilaszlo/suranyilaszlo.html\" id=\"navbar_tabor_bela_preszokratikus_szeminariumok\">Preszókratikus szemináriumok</a>\n' );
document.write( '      <a href=\"/taboradam/taboradam.html\" id=\"navbar_tabor_bela_egyeb_irasok\">Egyéb írások</a>\n' );
document.write( '      <a href=\"/horvathagnes/horvathagnes.html\" id=\"navbar_tabor_bela_szaz\">\"Tábor Béla 100\"</a>\n' );
document.write( '      <a href=\"/suranyilaszlo/suranyilaszlo.html\" id=\"navbar_tabor_belarol\">Tábor Béláról</a>\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '  </div>\n' );
document.write( '\n' );
document.write( '  <div class=\"dropdown\">\n' );
document.write( '    <button><a href=\"/mandystefania/mandystefania.html\" id=\"navbar_mandy_stefania\">Mándy Stefánia</a></button>\n' );
document.write( '\n' );
document.write( '    <div class=\"dropdown_content\">\n' );
document.write( '      <a href=\"/horvathagnes/horvathagnes.html\" id=\"navbar_mandy_stefania_eletrajz\">Életrajz</a>\n' );
document.write( '      <a href=\"/suranyilaszlo/suranyilaszlo.html\" id=\"navbar_mandy_stefania_versek\">Versek</a>\n' );
document.write( '      <a href=\"/taboradam/taboradam.html\" id=\"navbar_mandy_stefania_kepzomuveszeti_irasok\">Képzőművészeti írások</a>\n' );
document.write( '      <a href=\"/horvathagnes/horvathagnes.html\" id=\"navbar_mandy_stefania_egyeb_tanulmanyok\">Egyéb tanulmányok</a>\n' );
document.write( '      <a href=\"/suranyilaszlo/suranyilaszlo.html\" id=\"navbar_mandy_stefania_irasok_megemlekezesek\">Írások, megemlékezések</a>\n' );
document.write( '    </div>\n' );
document.write( '  </div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '  <div class=\"dropdown\">\n' );
document.write( '    <button class=\"tovabbi_szerzok\"><a id=\"navbar_tovabbi_szerzok\">További szerzők</a></button>\n' );
document.write( '\n' );
document.write( '    <div class=\"dropdown_content\">\n' );
document.write( '      <a href=\"/horvathagnes/horvathagnes.html\" id=\"navbar_horvath_agnes\">Horváth Ágnes</a>\n' );
document.write( '      <a href=\"/suranyilaszlo/suranyilaszlo.html\" id=\"navbar_suranyi_laszlo\">Surányi László</a>\n' );
document.write( '      <a href=\"/taboradam/taboradam.html\" id=\"navbar_tabor_adam\">Tábor Ádám</a>\n' );
document.write( '    </div>\n' );
document.write( '  </div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '<div class=\"konyvtar_language_selector_container\">\n' );
document.write( '    <div class=\"dropdown\">\n' );
document.write( '      <button class=\"konyvtar\"><a href=\"/konyvtar/konyvtar.html\" id=\"navbar_konyvtar\">Könyvtár</a></button>\n' );
document.write( '\n' );
document.write( '      <div class=\"dropdown_content\">\n' );
document.write( '        <a href=\"/konyvtar/konyvtar.html#irasok\" id=\"navbar_irasok\">Írások</a>\n' );
document.write( '        <a href=\"/konyvtar/konyvtar.html#galeria\" id=\"navbar_galeria\">Galéria</a>\n' );
document.write( '        <a href=\"/konyvtar/konyvtar.html#esemenyek\" id=\"navbar_esemenyek\">Események</a>\n' );
document.write( '      </div>\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '    <div class=\"dropdown\">\n' );
document.write( '      <button class=\"language_selector\"><a id=\"lang1\">Magyar</a></button>\n' );
document.write( '      <img class=\"language_flag\" src=\"/kepek/menu/magyar_zaszlo.svg\" alt=\"Magyar nyelv\">\n' );
document.write( '\n' );
document.write( '      <div class=\"dropdown_content\">\n' );
document.write( '        <button class=\"language_selection\" id=\"lang2\">English</button>\n' );
document.write( '        <button class=\"language_selection\" id=\"lang3\">Deutsch</button>\n' );
document.write( '        <button class=\"language_selection\" id=\"lang4\">Français</button>\n' );
document.write( '      </div>\n' );
document.write( '    </div>\n' );
document.write( '  </div>\n' );
document.write( '</nav' );
